title: CMSDAS Pre-School exercises 
description: These exercises cover the basic software skills you will need for the CMS Data Analysis school.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
